import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Zayka : QR Menus",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://watch-dog-pi.vercel.app/track.js" data-site="3d522349-235b-4f32-9130-61dccd87f008"></script>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
